[package]
name = "tokio-imap"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
license = "MIT/Apache-2.0"

[dependencies]
bytes = "0.4"
futures = "0.1"
native-tls = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-tls = "0.1"
