[package]
name = "tokio-imap"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
license = "MIT/Apache-2.0"

[dependencies]
bytes = "*"
futures = "*"
native-tls = "*"
tokio-core = "*"
tokio-io = "*"
tokio-tls = "*"
tokio-proto = "*"
